main/urls.py
from django.conf.urls import url, include

from main import views

app_name= 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

perfosap/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^almacen/', include('almacen.urls')),
    url(r'^procura/', include('procura.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]

procura/urls.py
from django.conf.urls import url

import procura.views
from . import views

app_name = 'procura'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # Providers related urls
    url(r'^provider/new/$', procura.views.new_provider, name='new-provider'),
    url(r'^provider/(?P<pk>\d+)/edit$', procura.views.edit_provider, name='edit-provider'),
    url(r'^provider/(?P<pk>\d+)/delete$', procura.views.DeleteProvider.as_view(), name='delete-provider'),
    url(r'^providers$', procura.views.provider_filter, name='providers'),
    url(r'^provider/(?P<pk>\d+)$', procura.views.ProviderDetailView.as_view(), name='provider-detail'),
    # Items nomenclature related urls
    url(r'^item/new$', procura.views.CreateItem.as_view(), name='new-item'),
    url(r'^item/(?P<pk>\d+)/edit$', procura.views.UpdateItem.as_view(), name='edit-item'),
    url(r'^item/(?P<pk>\d+)/delete$', procura.views.DeleteItem.as_view(), name='delete-item'),
    url(r'^items$', procura.views.item_filter, name='items'),
    url(r'^item/(?P<pk>\d+)$', procura.views.ItemDetailView.as_view(), name='item-detail'),
    # Contracts related urls
    url(r'^contracts$', procura.views.contract_filter, name='contracts'),
    url(r'^contract/(?P<pk>\d+)$', procura.views.ContractDetailView.as_view(), name='contract-detail'),
    url(r'^contract/(?P<pk>\d+)/edit$', procura.views.edit_contract, name='edit-contract'),
    url(r'^contract/new$', procura.views.new_contract, name='new-contract'),
    url(r'^contract/(?P<pk>\d+)/delete$', procura.views.DeleteContract.as_view(), name='delete-contract'),
]

procura/models.py
import datetime

from django.db import models

# Create your models here.
from django.urls import reverse


class LegalEntity(models.Model):
    name = models.CharField(max_length=100, help_text="Name")
    rif = models.CharField(max_length=11, help_text="RIF")
    address = models.TextField(help_text="Address")
    phone_num = models.CharField(max_length=15, help_text="Phone number")

    def __str__(self):
        pass


class Contract(models.Model):
    name = models.CharField(max_length=100, help_text="Name")
    number = models.CharField(max_length=50, help_text="Contract number")
    description = models.TextField(help_text="Contract description")
    start_date = models.DateField(help_text="Start date")
    expiry_date = models.DateField(help_text="Expiry date")

    class Meta:
        ordering = ["-expiry_date", "start_date", "name"]

    @property
    def is_expired(self):
        return self.expiry_date < datetime.date.today()

    def __str__(self):
        return "number: {0}, " \
               "name: \"{1}\", " \
               "starts: {2}, " \
               "expires: {3}."\
            .format(self.number, self.name, self.start_date, self.expiry_date)

    def get_absolute_url(self):
        return reverse('procura:contract-detail', args=[str(self.id)])


class Provider(LegalEntity):
    contract = models.ForeignKey(Contract)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return "name: \"{0}\", " \
               "RIF: {1}, " \
               "phone: {2}."\
            .format(self.name, self.rif, self.phone_num)

    def get_absolute_url(self):
        return reverse('procura:provider-detail', args=[str(self.id)])


class Item(models.Model):
    name = models.CharField(max_length=100, help_text="Name")
    serial = models.CharField(max_length=50, help_text="Serial No.")
    manufacturer = models.CharField(max_length=50, help_text="Manufacturer")
    provider = models.ForeignKey(Provider)

    class Meta:
        ordering = ["provider", "name"]

    def __str__(self):
        return "name: \"{0}\", " \
               "serial: {1}, " \
               "manufacturer: {2}," \
               "provider: {3}."\
            .format(self.name, self.serial, self.manufacturer, self.provider.name)

    def get_absolute_url(self):
        return reverse('procura:item-detail', args=[str(self.id)])

procura/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.forms import SelectDateWidget
from django.utils.translation import ugettext_lazy as _

from procura.models import Contract, Provider


class NewContractForm(forms.Form):
    number = forms.CharField()
    name = forms.CharField()
    description = forms.CharField(widget=forms.Textarea())
    start_date = forms.DateField(widget=SelectDateWidget())
    expiry_date = forms.DateField(widget=SelectDateWidget())

    def clean_expiry_date(self):
        exp_date = self.cleaned_data['expiry_date']
        st_date = self.cleaned_data['start_date']
        if exp_date is not None:
            if exp_date is not None:
                if exp_date <= st_date:
                    raise ValidationError(_("Invalid date - the contract can not expire before it started"
                                            " or expire the same day!"))

        return exp_date


class EditContractForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea, help_text="Enter contract description")
    start_date = forms.DateField(widget=SelectDateWidget(), help_text="Enter contract start date")
    expiry_date = forms.DateField(widget=SelectDateWidget(), help_text="Enter contract expiry date", required=False)

    def clean_expiry_date(self):
        exp_date = self.cleaned_data['expiry_date']
        st_date = self.cleaned_data['start_date']
        if exp_date is not None:
            if exp_date <= st_date:
                raise ValidationError(_("Invalid date - the contract can not expire before it started"
                                        " or expire the same day!"))

        return exp_date


class NewOrEditProviderForm(forms.Form):
    name = forms.CharField()
    rif = forms.CharField(max_length=11)
    address = forms.CharField(widget=forms.Textarea())
    phone_num = forms.CharField(max_length=13)
    contract = forms.ModelChoiceField(queryset=Contract.objects.all())

    def clean_phone_num(self):
        ph_num = self.cleaned_data['phone_num']
        p = re.compile(r'^\+\d{10,13}$')
        if not p.search(ph_num):
            raise ValidationError(_('Invalid phone number: amust start from \+ and the numeric part be '
                                    '10 - 13 digits long'))

        return ph_num

    def clean_rif(self):
        rif = self.cleaned_data['rif']
        p = re.compile(r'^(E-|P-|J-|V-|G-|C-)\d{9}$')
        if not p.search(rif):
            raise ValidationError(_('Invalid RIF format: must begin from one of these: "E-", "P-", '
                                    '"J-", "V-", "G-" or "C-" '
                                    'and the numeric part be 9 digits long'))

        return rif


class NewOrEditItemForm(forms.Form):
    serial = forms.CharField()
    name = forms.CharField()
    manufacturer = forms.CharField()
    provider = forms.ModelChoiceField(queryset=Provider.objects.all())

procura/views.py
import datetime

from django.contrib.auth.decorators import permission_required, login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import DeleteView, CreateView, UpdateView

from procura.filters import ContractFilter, ProviderFilter, ItemsNomenclatureFilter
from procura.forms import NewContractForm, EditContractForm, NewOrEditProviderForm
from procura.models import Contract, Provider, Item


def index(request):
    return render(request, 'procura_static_pages/index.html')


@permission_required('procura.create_contract')
def new_contract(request):
    if request.method == 'POST':
        form = NewContractForm(request.POST)
        if form.is_valid():
            contract = Contract()
            contract.number = form.cleaned_data['number']
            contract.name = form.cleaned_data['name']
            contract.description = form.cleaned_data['description']
            contract.start_date = form.cleaned_data['start_date']
            contract.expiry_date = form.cleaned_data['expiry_date']
            contract.save()
            return HttpResponseRedirect(reverse('procura:contracts'))
    else:
        today = datetime.date.today()
        form = NewContractForm(initial={
            'start_date': today,
            'expiry_date': datetime.date(today.year + 1, today.month, today.day)
        })
        return render(request, 'procura/contract_new.html', {'form':form})


@permission_required('procura.change_contract')
def edit_contract(request, pk):
    contract = get_object_or_404(Contract, pk=pk)
    if request.method == 'POST':
        form = EditContractForm(request.POST)
        if form.is_valid():
            contract.description = form.cleaned_data['description']
            contract.start_date = form.cleaned_data['start_date']
            contract.expiry_date = form.cleaned_data['expiry_date']
            contract.save()
            return HttpResponseRedirect(reverse('procura:contract-detail', args=[pk]))
    else:
        today = datetime.date.today()
        form = EditContractForm(initial={
            'description': contract.description,
            'start_date': today,
            'expiry_date': contract.expiry_date
        })
    return render(request, 'procura/contract_edit.html', {'form': form, 'contract': contract})


@method_decorator(login_required, name='dispatch')
class DeleteContract(DeleteView):
    model = Contract
    success_url = reverse_lazy('procura:contracts')


# @method_decorator(login_required, name='dispatch')
# class ContractListView(generic.ListView):
#     model = Contract
#     paginate_by = 10

@login_required()
def contract_filter(request):
    f = ContractFilter(request.GET, queryset=Contract.objects.all())
    return render_to_response('procura/contract_list.html', {'filter': f})



@method_decorator(login_required, name='dispatch')
class ContractDetailView(generic.DetailView):
    model = Contract


@login_required
def new_provider(request):
    if request.method == 'POST':
        form = NewOrEditProviderForm(request.POST)
        if form.is_valid():
            provider = Provider()
            provider.name = form.cleaned_data['name']
            provider.rif = form.cleaned_data['rif']
            provider.address = form.cleaned_data['address']
            provider.phone_num = form.cleaned_data['phone_num']
            provider.contract = form.cleaned_data['contract']
            provider.save()
            return HttpResponseRedirect(reverse('procura:providers'))
    else:
        form = NewOrEditProviderForm()

    return render(request, 'procura/provider_new.html', {'form':form})


@login_required
def edit_provider(request, pk):
    provider = get_object_or_404(Provider, pk=pk)
    if request.method == 'POST':
        form = NewOrEditProviderForm(request.POST)
        if form.is_valid():
            provider.name = form.cleaned_data['name']
            provider.rif = form.cleaned_data['rif']
            provider.address = form.cleaned_data['address']
            provider.phone_num = form.cleaned_data['phone_num']
            provider.contract = form.cleaned_data['contract']
            provider.save()
            return HttpResponseRedirect(reverse('procura:provider-detail', args=[pk]))
    else:
        form = NewOrEditProviderForm(initial={
            'name': provider.name,
            'rif': provider.rif,
            'address': provider.address,
            'phone_num': provider.phone_num,
            'contract': provider.contract
        })

    return render(request, 'procura/provider_edit.html', {'form': form, 'provider': provider})


@method_decorator(login_required, name='dispatch')
class DeleteProvider(DeleteView):
    model = Provider
    success_url = reverse_lazy('procura:providers')


# @method_decorator(login_required, name='dispatch')
# class ProviderListView(generic.ListView):
#     model = Provider
#     paginate_by = 10

@login_required()
def provider_filter(request):
    f = ProviderFilter(request.GET, queryset=Provider.objects.all())
    return render_to_response('procura/provider_list.html', {'filter': f})


@method_decorator(login_required, name='dispatch')
class ProviderDetailView(generic.DetailView):
    model = Provider


@method_decorator(login_required, name='dispatch')
class CreateItem(CreateView):
    model = Item
    fields = '__all__'


@method_decorator(login_required, name='dispatch')
class UpdateItem(UpdateView):
    model = Item
    fields = '__all__'


@method_decorator(login_required, name='dispatch')
class DeleteItem(DeleteView):
    model = Item
    success_url = reverse_lazy('procura:items')


# @method_decorator(login_required, name='dispatch')
# class ItemListView(generic.ListView):
#     model = Item
#     paginate_by = 10

@login_required()
def item_filter(request):
    f = ItemsNomenclatureFilter(request.GET, queryset=Item.objects.all())
    return render_to_response('procura/item_list.html', {'filter': f})


@method_decorator(login_required, name='dispatch')
class ItemDetailView(generic.DetailView):
    model = Item

procura/templates/procura/contract_confirm_delete.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Delete contract </h2>

{% endblock %}

{% block content %}

    <p>Are you sure want to delete contract {{ contract.number }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <p><a href="{% url 'procura:contracts' %}">Back to list</a></p>
        <input type="submit" value="Yes, delete.">
    </form>

{% endblock %}

procura/templates/procura/contract_detail.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Contract details</h2>

{% endblock %}

{% block content %}

	<p><strong>Contract No.: </strong> {{ contract.number }} </p>
	<p><strong>Name: </strong> {{ contract.name }} </p>
	<p><strong>Starts: </strong> {{ contract.start_date }} </p>
	<p style="color: {% if contract.is_expired %}#f75526{% endif %}"><strong>{% if contract.is_expired %}Expired{% else %}Expires {% endif %}: </strong> {% if contract.expiry_date == None %} Indefinite {% else %} {{contract.expiry_date}} {% endif %} </p>
	<p><strong>Description: </strong> {{ contract.description }} </p>
    <p>
        <a href="{% url 'procura:edit-contract' contract.pk %}">Edit</a> |
        <a href="{% url 'procura:delete-contract' contract.pk %}">Delete</a>
    </p>
    <p><a href="{% url 'procura:contracts' %}">To contracts list</a></p>

{% endblock %}

procura/templates/procura/contract_edit.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Edit contract No. {{ contract.number }} </h2>

{% endblock %}

{% block content %}
    <h4><strong>{{ contract.name }} </strong></h4>
    <form action="{% url 'procura:edit-contract' contract.pk %}" method="post">
        {% csrf_token %}

        <table>
            {{ form }}
        </table>

        <input type="submit" value="Submit">
    </form>

{% endblock %}

procura/templates/procura/contract_list.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Contracts {{ contract.number }} </h2>

{% endblock %}

{% block content %}
    <form method="get">
        {{ filter.form }}
        <button type="submit">Filter</button>
    </form>

    <br>
    <p><a href="{% url 'procura:new-contract' %}">Add new</a></p>

    <table style="width:100%">
        <tr style="text-align:center">
            <th>No.</th>
            <th>Name</th>
            <th>Starts</th>
            <th>Expires</th>
        </tr>

        {% for contract in filter.qs %}

            <tr style="color:{% if contract.is_expired %} #f75526 {% endif %}">
                <td>
                    <a href="{% url 'procura:contract-detail' contract.pk %}"> {{ contract.number }} </a>
                </td>
                <td>{{ contract.name }}</td>
                <td>{{ contract.start_date }}</td>
                <td>
                    {% if contract.expiry_date == None %} Indefinite {% else %}
                        {{ contract.expiry_date }} {% endif %}
                </td>
            </tr>

        {% endfor %}
    </table>
    {% if is_paginated %}

        <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}"><--</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">--></a>
                    {% endif %}
                </span>
        </div>

    {% endif %}

{% endblock %}

procura/templates/procura/contract_new.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">New contract </h2>

{% endblock %}

{% block content %}

    <form action="{% url 'procura:new-contract' %}" method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

procura/templates/procura/item_confirm_delete.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Delete item nomenclature </h2>

{% endblock %}

{% block content %}

    <p>Are you sure want to delete item {{ item.serial }}, {{ item.name }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <p><a href="{% url 'procura:items' %}">Back to list</a></p>
        <input type="submit" value="Yes, delete.">
    </form>

{% endblock %}

procura/templates/procura/item_detail.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Item details </h2>

{% endblock %}

{% block content %}

	<p><strong>Serial: </strong> {{ item.serial }} </p>
	<p><strong>Name: </strong> {{ item.name }} </p>
	<p><strong>Manufacturer: </strong> {{ item.manufacturer }} </p>
    <p><strong>Provider: </strong> <a href="{% url 'procura:provider-detail' item.provider.pk%}"> {{item.provider.name}}</a> </p>

    <p>
        <a href="{% url 'procura:edit-item' item.pk %}">Edit</a> |
        <a href="{% url 'procura:delete-item' item.pk %}">Delete</a>
    </p>
    <p><a href="{% url 'procura:items' %}">To items nomenclature list</a></p>

{% endblock %}

procura/templates/procura/item_form.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Item add/edit </h2>

{% endblock %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}

        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="Submit"/>

    </form>

{% endblock %}

procura/templates/procura/item_list.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Item nomenclature</h2>

{% endblock %}

{% block content %}

    <form method="get">
        {{ filter.form }}
        <button type="submit">Filter</button>
    </form>

    <br>
    <p><a href="{% url 'procura:new-item' %}">Add new</a></p>

    <table style="width:100%">
        <tr>
            <th>Serial</th>
            <th>Name</th>
            <th>Manufacturer</th>
            <th>Provider</th>
        </tr>

        {% for item in filter.qs %}

            <tr>
                <td>
                    <a href="{% url 'procura:item-detail' item.pk %}"> {{ item.serial }} </a>
                </td>
                <td>{{ item.name }}</td>
                <td>{{ item.manufacturer }}</td>
                <td>
                    <a href="{% url 'procura:provider-detail' item.provider.pk %}"> {{ item.provider.name }} </a>
                </td>
            </tr>

        {% endfor %}
    </table>
    {% if is_paginated %}

        <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}"><--</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">--></a>
                    {% endif %}
                </span>
        </div>

    {% endif %}

{% endblock %}

procura/templates/procura/provider_confirm_delete.html
{% extends 'procura_static_pages/procura_base_template.html' %}
{% block content %}

    {% block header %}

    <h2 id="center">Delete provider </h2>

{% endblock %}

    <p>Are you sure want to delete provider {{ provider.name }}, {{ provider.rif }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <p><a href="{% url 'procura:providers' %}">Back to list</a></p>
        <input type="submit" value="Yes, delete.">
    </form>

{% endblock %}

procura/templates/procura/provider_detail.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Provider details </h2>

{% endblock %}

{% block content %}
	
	<p><strong>Name: </strong> {{ provider.name }} </p>
	<p><strong>Rif: </strong> {{ provider.rif }} </p>
	<p><strong>Phone: </strong> {{provider.phone_num}} </p>
	<p><strong>Address: </strong> {{ provider.address }} </p>
	<p><strong>Contract: </strong> <a href="{% url 'procura:contract-detail' provider.contract.pk %}"> {{ provider.contract.number }} </a> </p>

    <p>
        <a href="{% url 'procura:edit-provider' provider.pk %}">Edit</a> |
        <a href="{% url 'procura:delete-provider' provider.pk %}">Delete</a>
    </p>
    <p><a href="{% url 'procura:providers' %}">To providers list</a></p>

{% endblock %}

procura/templates/procura/provider_edit.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Provider add/edit </h2>

{% endblock %}

{% block content %}

    <form action="{% url 'procura:edit-provider' provider.pk %}" method="post">
        {% csrf_token %}

        <table>
            {{ form }}
        </table>

        <input type="submit" value="Submit"/>

    </form>

{% endblock %}

procura/templates/procura/provider_list.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Providers</h2>

{% endblock %}

{% block content %}
    <form method="get">
        {{ filter.form }}
        <button type="submit">Filter</button>
    </form>

    <br>
    <p><a href="{% url 'procura:new-provider' %}">Add new</a></p>

        <table style="width:100%">
            <tr>
                <th>Name</th>
                <th>RIF</th>
                <th>Phone</th>
                <th>Contract No.</th>
            </tr>

            {% for provider in filter.qs %}

                <tr>
                    <td>
                        <a href="{% url 'procura:provider-detail' provider.pk %}"> {{ provider.name }} </a>
                    </td>
                    <td>{{ provider.rif }}</td>
                    <td>{{ provider.phone_num }}</td>
                    <td>
                        <a href="{% url 'procura:contract-detail' provider.contract.pk %}"> {{ provider.contract.number }} </a>
                    </td>
                </tr>

            {% endfor %}
        </table>
        {% if is_paginated %}

            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}"><--</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">--></a>
                    {% endif %}
                </span>
            </div>

        {% endif %}

{% endblock %}

procura/templates/procura/provider_new.html
{% extends 'procura_static_pages/procura_base_template.html' %}

{% block header %}

    <h2 id="center">Provider add/edit </h2>

{% endblock %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}

        <table>
            {{ form }}
        </table>

        <input type="submit" value="Submit"/>

    </form>

{% endblock %}