almacen/urls.py
from django.conf.urls import url

from . import views

app_name = 'almacen'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # Stored items related urls
    url(r'^storeditem/new$', views.new_storeditem, name='new-storeditem'),
    url(r'^storeditem/(?P<pk>\d+)/edit$', views.edit_storeditem, name='edit-storeditem'),
    url(r'^storeditem/(?P<pk>\d+)/delete$', views.DeleteStoredItem.as_view(), name='delete-storeditem'),
    url(r'^storeditems$', views.storeditem_filter, name='storeditems'),
    url(r'^storeditem/(?P<pk>\d+)$', views.StoredItemDetailView.as_view(), name='storeditem-detail'),
]

main/urls.py
from django.conf.urls import url, include

from main import views

app_name= 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

perfosap/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^almacen/', include('almacen.urls')),
    url(r'^procura/', include('procura.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]

almacen/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
from procura.models import Item


class StoredItem(models.Model):
    item = models.ForeignKey(Item)
    quantity = models.IntegerField(default=0)

    class Meta:
        ordering = ["item"]

    def __str__(self):
        return "{0} - {1}, {2} pcs.".format(self.item.serial, self.item.name, self.quantity)

    def get_absolute_url(self):
        return reverse('almacen:storeditem-detail', args=[str(self.id)])

almacen/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

# Contract related forms
from procura.models import Item


# Stored items related forms
class NewOrEditStoredItemForm(forms.Form):
    item = forms.ModelChoiceField(queryset=Item.objects.all())
    quantity = forms.IntegerField()

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        if quantity < 0:
            raise ValidationError(_("Items quantity can not be negative!"))
        return quantity

almacen/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response
from django.utils.decorators import method_decorator
from django.views import generic
# Create your views here.
from django.views.generic import DeleteView

from almacen.filters import StoredItemsFilter
from almacen.models import StoredItem
from procura.models import Provider
from .forms import NewOrEditStoredItemForm
from .services import store_item


def index(request):
    stored_items_num = len([x for x in StoredItem.objects.all() if x.quantity > 0])
    providers_num = Provider.objects.all().count()

    return render(request,
                  'almacen_static_pages/index.html',
                  context={
                      'stored_items_num': stored_items_num,
                      'providers_num': providers_num
                  })


# Stored items related ---------------------------------------------------------------------
@login_required
def new_storeditem(request):
    if request.method == 'POST':
        form = NewOrEditStoredItemForm(request.POST)
        if form.is_valid():
            storeditem = StoredItem()
            storeditem.item = form.cleaned_data['item']
            storeditem.quantity = form.cleaned_data['quantity']
            store_item(storeditem)
            return HttpResponseRedirect(reverse('almacen:storeditems'))
    else:
        form = NewOrEditStoredItemForm()

    return render(request, 'almacen/storeditem_new.html', {'form':form})


@login_required
def edit_storeditem(request, pk):
    storeditem = get_object_or_404(StoredItem, pk=pk)
    if request.method == 'POST':
        form = NewOrEditStoredItemForm(request.POST)
        if form.is_valid():
            storeditem.item = form.cleaned_data['item']
            storeditem.quantity = form.cleaned_data['quantity']
            storeditem.save()
            return HttpResponseRedirect(reverse('almacen:storeditem-detail', args=[pk]))
    else:
        form = NewOrEditStoredItemForm(initial={
            'item': storeditem.item,
            'quantity': storeditem.quantity,
        })

    return render(request, 'almacen/storeditem_edit.html', {'form': form, 'storeditem': storeditem})


@method_decorator(login_required, name='dispatch')
class DeleteStoredItem(DeleteView):
    model = StoredItem
    success_url = reverse_lazy('almacen:storeditems')


# @method_decorator(login_required, name='dispatch')
# class StoredItemListView(generic.ListView):
#     model = StoredItem
#     paginate_by = 10


@login_required()
def storeditem_filter(request):
    f = StoredItemsFilter(request.GET, queryset=StoredItem.objects.all())
    return render_to_response('almacen/storeditem_list.html', {'filter': f})



@method_decorator(login_required, name='dispatch')
class StoredItemDetailView(generic.DetailView):
    model = StoredItem

almacen/templates/almacen_static_pages/almacen_base_template.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Almacen Application</title>{% endblock %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<header id="center">
    <div style="text-align: right">
        {% if user.is_authenticated %}
            {{ user.get_username }}
            -
            <a href="{% url 'logout' %}?next={{ request.path }}">logout</a>
        {% else %}
            <p><a href="{% url 'login' %}?next={{ request.path }}">Login</a></p>
        {% endif %}
        {% block header %} {% endblock %}
    </div>
</header>
<div class="container-fluid">
    <div class="content">
        <div class="row">
            <div class="col-sm-2 sidenav">
                <h4>Options: </h4>
                {% block sidebar %}
                    <ul class="nav nav-pills nav-stacked">
                        <li><strong><a href="{% url 'main:index' %}">To main page</a></strong></li>
                        <li><a href="{% url 'almacen:index' %}">Home</a></li>
                        <li><a href="{% url 'almacen:storeditems' %}">Stored items</a></li>
                    </ul>
                {% endblock %}
            </div>
            <div class="col-sm-9 ">
                <br>
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
<footer id="center" class="container-fluid">
    <p>
        PerfoSAP Package<br>
        For Perforosven, S.A<br>
        created by caesar_84
    </p>
</footer>
</body>
</html>

almacen/templates/almacen_static_pages/index.html
{% extends 'almacen_static_pages/almacen_base_template.html' %}

{% block header %}

    <h2 id="center">Welcome to Almacen Application!</h2>

{% endblock %}

{% block content %}


    <p>
        Glad to see you in the Almacen Application!<br>
        This application is designed to ease your work with stored materials and components. Please, use the navigation
        bar for work:<br>
    </p>
    <p>
    <li>Store menu to handle the items movements</li>
    </p>
    <p>
        Actually, there {% if stored_items_num > 1 %} are {% else %} is {% endif %}

        {{ stored_items_num }} stock {% if stored_items_num > 1 %} items {% else %} item {% endif %}

        in the store from {{ providers_num }}

        {% if providers_num > 1 %} providers {% else %} provider {% endif %}
    </p>

{% endblock %}