almacen/urls.py
from django.conf.urls import url

from . import views

app_name = 'almacen'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # Stored items related urls
    url(r'^storeditem/new$', views.new_storeditem, name='new-storeditem'),
    url(r'^storeditem/(?P<pk>\d+)/edit$', views.edit_storeditem, name='edit-storeditem'),
    url(r'^storeditem/(?P<pk>\d+)/delete$', views.DeleteStoredItem.as_view(), name='delete-storeditem'),
    url(r'^storeditems$', views.storeditem_filter, name='storeditems'),
    url(r'^storeditem/(?P<pk>\d+)$', views.StoredItemDetailView.as_view(), name='storeditem-detail'),
]

main/urls.py
from django.conf.urls import url, include

from main import views

app_name= 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

perfosap/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^almacen/', include('almacen.urls')),
    url(r'^procura/', include('procura.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]

procura/urls.py
from django.conf.urls import url

import procura.views
from . import views

app_name = 'procura'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # Providers related urls
    url(r'^provider/new/$', procura.views.new_provider, name='new-provider'),
    url(r'^provider/(?P<pk>\d+)/edit$', procura.views.edit_provider, name='edit-provider'),
    url(r'^provider/(?P<pk>\d+)/delete$', procura.views.DeleteProvider.as_view(), name='delete-provider'),
    url(r'^providers$', procura.views.provider_filter, name='providers'),
    url(r'^provider/(?P<pk>\d+)$', procura.views.ProviderDetailView.as_view(), name='provider-detail'),
    # Items nomenclature related urls
    url(r'^item/new$', procura.views.CreateItem.as_view(), name='new-item'),
    url(r'^item/(?P<pk>\d+)/edit$', procura.views.UpdateItem.as_view(), name='edit-item'),
    url(r'^item/(?P<pk>\d+)/delete$', procura.views.DeleteItem.as_view(), name='delete-item'),
    url(r'^items$', procura.views.item_filter, name='items'),
    url(r'^item/(?P<pk>\d+)$', procura.views.ItemDetailView.as_view(), name='item-detail'),
    # Contracts related urls
    url(r'^contracts$', procura.views.contract_filter, name='contracts'),
    url(r'^contract/(?P<pk>\d+)$', procura.views.ContractDetailView.as_view(), name='contract-detail'),
    url(r'^contract/(?P<pk>\d+)/edit$', procura.views.edit_contract, name='edit-contract'),
    url(r'^contract/new$', procura.views.new_contract, name='new-contract'),
    url(r'^contract/(?P<pk>\d+)/delete$', procura.views.DeleteContract.as_view(), name='delete-contract'),
]

almacen/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
from procura.models import Item


class StoredItem(models.Model):
    item = models.ForeignKey(Item)
    quantity = models.IntegerField(default=0)

    class Meta:
        ordering = ["item"]

    def __str__(self):
        return "{0} - {1}, {2} pcs.".format(self.item.serial, self.item.name, self.quantity)

    def get_absolute_url(self):
        return reverse('almacen:storeditem-detail', args=[str(self.id)])

almacen/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

# Contract related forms
from procura.models import Item


# Stored items related forms
class NewOrEditStoredItemForm(forms.Form):
    item = forms.ModelChoiceField(queryset=Item.objects.all())
    quantity = forms.IntegerField()

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        if quantity < 0:
            raise ValidationError(_("Items quantity can not be negative!"))
        return quantity

almacen/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, render_to_response
from django.utils.decorators import method_decorator
from django.views import generic
# Create your views here.
from django.views.generic import DeleteView

from almacen.filters import StoredItemsFilter
from almacen.models import StoredItem
from procura.models import Provider
from .forms import NewOrEditStoredItemForm
from .services import store_item


def index(request):
    stored_items_num = len([x for x in StoredItem.objects.all() if x.quantity > 0])
    providers_num = Provider.objects.all().count()

    return render(request,
                  'almacen_static_pages/index.html',
                  context={
                      'stored_items_num': stored_items_num,
                      'providers_num': providers_num
                  })


# Stored items related ---------------------------------------------------------------------
@login_required
def new_storeditem(request):
    if request.method == 'POST':
        form = NewOrEditStoredItemForm(request.POST)
        if form.is_valid():
            storeditem = StoredItem()
            storeditem.item = form.cleaned_data['item']
            storeditem.quantity = form.cleaned_data['quantity']
            store_item(storeditem)
            return HttpResponseRedirect(reverse('almacen:storeditems'))
    else:
        form = NewOrEditStoredItemForm()

    return render(request, 'almacen/storeditem_new.html', {'form':form})


@login_required
def edit_storeditem(request, pk):
    storeditem = get_object_or_404(StoredItem, pk=pk)
    if request.method == 'POST':
        form = NewOrEditStoredItemForm(request.POST)
        if form.is_valid():
            storeditem.item = form.cleaned_data['item']
            storeditem.quantity = form.cleaned_data['quantity']
            storeditem.save()
            return HttpResponseRedirect(reverse('almacen:storeditem-detail', args=[pk]))
    else:
        form = NewOrEditStoredItemForm(initial={
            'item': storeditem.item,
            'quantity': storeditem.quantity,
        })

    return render(request, 'almacen/storeditem_edit.html', {'form': form, 'storeditem': storeditem})


@method_decorator(login_required, name='dispatch')
class DeleteStoredItem(DeleteView):
    model = StoredItem
    success_url = reverse_lazy('almacen:storeditems')


# @method_decorator(login_required, name='dispatch')
# class StoredItemListView(generic.ListView):
#     model = StoredItem
#     paginate_by = 10


@login_required()
def storeditem_filter(request):
    f = StoredItemsFilter(request.GET, queryset=StoredItem.objects.all())
    return render_to_response('almacen/storeditem_list.html', {'filter': f})



@method_decorator(login_required, name='dispatch')
class StoredItemDetailView(generic.DetailView):
    model = StoredItem

almacen/templates/almacen/storeditem_confirm_delete.html
{% extends 'almacen_static_pages/almacen_base_template.html' %}

{% block header %}

    <h2 id="center">Delete stored item </h2>

{% endblock %}

{% block content %}

    <p>Are you sure want to delete a stored item {{ storeditem.item.serial }}, {{ storeditem.item.name }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <p><a href="{% url 'almacen:storeditems' %}">Back to list</a></p>
        <input type="submit" value="Yes, delete.">
    </form>

{% endblock %}

almacen/templates/almacen/storeditem_detail.html
{% extends 'almacen_static_pages/almacen_base_template.html' %}

{% block header %}

    <h2 id="center">Stocked item details </h2>

{% endblock %}

{% block content %}

    <p><strong>Serial: </strong> <a
            href="{% url 'procura:item-detail' storeditem.item.pk %}"> {{ storeditem.item.serial }} </a></p>
    <p><strong>Name: </strong> {{ storeditem.item.name }} </p>
    <p style="color: {% if storeditem.quantity == 0 %}#f75526{% endif %}"><strong>Quantity: </strong> {{ storeditem.quantity }} </p>

    <p>
        <a href="{% url 'almacen:edit-storeditem' storeditem.pk %}">Edit</a> |
        <a href="{% url 'almacen:delete-storeditem' storeditem.pk %}">Delete</a>
    </p>
    <p><a href="{% url 'almacen:storeditems' %}">To stored items list</a></p>

{% endblock %}

almacen/templates/almacen/storeditem_edit.html
{% extends 'almacen_static_pages/almacen_base_template.html' %}

{% block header %}

    <h2 id="center">Stocked item add/delete </h2>

{% endblock %}

{% block content %}

    <form action="{% url 'almacen:edit-storeditem' storeditem.pk %}" method="post">
        {% csrf_token %}

        <table>
            {{ form }}
        </table>

        <input type="submit" value="Submit"/>

    </form>

{% endblock %}

almacen/templates/almacen/storeditem_list.html
{% extends 'almacen_static_pages/almacen_base_template.html' %}

{% block header %}

    <h2 id="center">Stored items list </h2>

{% endblock %}

{% block content %}

    <form method="get">
        {{ filter.form }}
        <button type="submit">Filter</button>
    </form>

    <br>
    <p><a href="{% url 'almacen:new-storeditem' %}">Add new</a></p>

        <table style="width:100%">
            <tr>
                <th>Serial</th>
                <th>Name</th>
                <th>Quantity</th>
                <th>Manufacturer</th>
                <th>Provider</th>
            </tr>

            {% for storeditem in filter.qs %}

                <tr style="color: {% if storeditem.quantity == 0 %}#f75526{% endif %}">
                    <td>
                        <a href="{% url 'almacen:storeditem-detail' storeditem.pk %}"> {{ storeditem.item.serial }} </a>
                    </td>
                    <td>{{ storeditem.item.name }}</td>
                    <td>{{ storeditem.quantity }}</td>
                    <td>{{ storeditem.item.manufacturer }}</td>
                    <td>
                        <a href="{% url 'procura:provider-detail' storeditem.item.provider.pk %}">{{ storeditem.item.provider.name }}</a>
                    </td>
                </tr>

            {% endfor %}
        </table>
        {% if is_paginated %}

            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}"><--</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">--></a>
                    {% endif %}
                </span>
            </div>

        {% endif %}

{% endblock %}

almacen/templates/almacen/storeditem_new.html
{% extends 'almacen_static_pages/almacen_base_template.html' %}

{% block header %}

    <h2 id="center">Stocked item add/delete </h2>

{% endblock %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}

        <table>
            {{ form }}
        </table>

        <input type="submit" value="Submit"/>

    </form>

{% endblock %}