almacen/urls.py
from django.conf.urls import url

from . import views

app_name = 'almacen'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # Stored items related urls
    url(r'^storeditem/new$', views.new_storeditem, name='new-storeditem'),
    url(r'^storeditem/(?P<pk>\d+)/edit$', views.edit_storeditem, name='edit-storeditem'),
    url(r'^storeditem/(?P<pk>\d+)/delete$', views.DeleteStoredItem.as_view(), name='delete-storeditem'),
    url(r'^storeditems$', views.storeditem_filter, name='storeditems'),
    url(r'^storeditem/(?P<pk>\d+)$', views.StoredItemDetailView.as_view(), name='storeditem-detail'),
]

main/urls.py
from django.conf.urls import url, include

from main import views

app_name= 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

perfosap/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
    url(r'^almacen/', include('almacen.urls')),
    url(r'^procura/', include('procura.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]

procura/urls.py
from django.conf.urls import url

import procura.views
from . import views

app_name = 'procura'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # Providers related urls
    url(r'^provider/new/$', procura.views.new_provider, name='new-provider'),
    url(r'^provider/(?P<pk>\d+)/edit$', procura.views.edit_provider, name='edit-provider'),
    url(r'^provider/(?P<pk>\d+)/delete$', procura.views.DeleteProvider.as_view(), name='delete-provider'),
    url(r'^providers$', procura.views.provider_filter, name='providers'),
    url(r'^provider/(?P<pk>\d+)$', procura.views.ProviderDetailView.as_view(), name='provider-detail'),
    # Items nomenclature related urls
    url(r'^item/new$', procura.views.CreateItem.as_view(), name='new-item'),
    url(r'^item/(?P<pk>\d+)/edit$', procura.views.UpdateItem.as_view(), name='edit-item'),
    url(r'^item/(?P<pk>\d+)/delete$', procura.views.DeleteItem.as_view(), name='delete-item'),
    url(r'^items$', procura.views.item_filter, name='items'),
    url(r'^item/(?P<pk>\d+)$', procura.views.ItemDetailView.as_view(), name='item-detail'),
    # Contracts related urls
    url(r'^contracts$', procura.views.contract_filter, name='contracts'),
    url(r'^contract/(?P<pk>\d+)$', procura.views.ContractDetailView.as_view(), name='contract-detail'),
    url(r'^contract/(?P<pk>\d+)/edit$', procura.views.edit_contract, name='edit-contract'),
    url(r'^contract/new$', procura.views.new_contract, name='new-contract'),
    url(r'^contract/(?P<pk>\d+)/delete$', procura.views.DeleteContract.as_view(), name='delete-contract'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'static_page/index.html')

main/templates/static_page/index.html
{% extends 'static_page/main_base_template.html' %}

{% block title %}
    <title>Almacen Application</title>
{% endblock %}

{% block content %}
    <p>
        Glad to see you in the PerfoSAP Package!<br>
        This application is designed to ease your work and records in the company. Please, use the
        navigation
        bar for work:<br>
    </p>

    <li>Almacen menu to move to Almacen App</li>
    <li>Procura menu to move to Procura App</li>
{% endblock %}

main/templates/static_page/main_base_template.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %} {% endblock %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<header id="center">
    <div style="text-align: right">
        {% if user.is_authenticated %}
            {{ user.get_username }}
            -
            <a href="{% url 'logout' %}?next={{ request.path }}">logout</a>
        {% else %}
            <p><a href="{% url 'login' %}?next={{ request.path }}">Login</a></p>
        {% endif %}
        <h2 id="center">Welcome to PerfoSAP Package!</h2>
    </div>
</header>
<div class="container-fluid">
    <div class="content">
        <div class="row">
            <div class="col-sm-2 sidenav">
                <h4>Options: </h4>
                {% block sidebar %}
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'almacen:index' %}">Almacen</a></li>
                        <li><a href="{% url 'procura:index' %}">Procura</a></li>
                    </ul>
                {% endblock %}
            </div>
            <div class="col-sm-9 ">
                <br>
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
</div>
<footer id="center" class="container-fluid">
    <p>
        PerfoSAP Package<br>
        For Perforosven, S.A<br>
        created by caesar_84
    </p>
</footer>
</body>
</html>